### ISSUE TITLE
Allow `serialize_data.py` accept path for proposed endpoints docs as command line argument

### ISSUE THREAD

**Issue by CuriousLearner** [CuriousLearner/api-stub#1]
The `serialize_data.py` file currently has `proposed_endpoints.md` file hard-coded.

Modify this file to accept a path for proposed endpoints docs as command line argument.

This is a beginner-friendly issue.

**Comment by mansiag** [comment]
I would like to work on this issue

**Comment by mansiag** [comment]
I would like to work on this issue.

**Comment by CuriousLearner** [comment]
Sure Mansi, 

Please go ahead and link the PR to the issue once you're done.

**Comment by mansiag** [comment]
#4

**Comment by mansiag** [comment]
Solved issue in #4

**Comment by CuriousLearner** [comment]
Fixed in #4
